"""Correct interpretation, not numerical result files. Verbatim change ledger."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];p=ROOT/'paper/main.tex';s=p.read_text();changes=[]
def fix(old,new):
 global s
 assert old in s,old[:100]
 changes.append({'before':old,'after':new});s=s.replace(old,new)
fix("($3.2\\times$)","(difference $1.52$ standardized score units)") if "($3.2\\times$)" in s else None
fix("(3.2$\\times$)","(difference 1.52 standardized score units)")
fix("direct evidence that CodonOpt's advantage lives in sequence context that single-codon statistics (CAI's whole basis) cannot see, not in the CNN scoring its own bias", "evidence of evaluator-dependent rankings, not a causal demonstration of sequence-context expression gains. These evaluators share abundance labels; disagreement does not exclude surrogate-objective bias")
fix("A learned sequence-to-expression objective beats the field-standard codon optimizer on its own published benchmark by 3.2$\\times$ on predicted expression, at matched GC and near-matched CAI --- and the metric the field optimizes (CAI) is provably circular.","A learned objective raises its own predicted-expression score on a published sequence benchmark. The historical checkpoint is unrecoverable; a separately source-pinned checkpoint reproduces a within-model ranking but does not establish a measured expression fold gain. Maximizing CAI by a highest-frequency-codon construction is an objective tautology, not proof that CAI is biologically useless.")
fix("\\textbf{The biological insight first.} Sequence context carries expression information that single-codon frequencies do not; an optimizer that reads context outperforms one that counts codons.","\\textbf{The scoped inference.} Different trained evaluators assign different rankings to optimized sequences. This does not establish how much biological expression information comes from sequence context rather than codon usage, nor a causal expression gain.")
fix("bag-of-codons metrics are blind to the context that carries CodonOpt's gain", "the ranking depends on evaluator choice; the ridge evaluator itself uses codon-frequency features")
fix("and demonstrate a learned-expression objective that beats ICOR on its own benchmark by 3.2$\\times$ on predicted expression at matched GC and near-matched CAI.","and report a learned-expression objective with higher within-model standardized scores on the published benchmark. Ratios of z-scores are not expression fold changes; the uncommitted historical checkpoint is not reproducible, and the later source-pinned rescore is a separate experiment.")
fix("Ours concedes CAI to ICOR by 5\\% and wins predicted expression by $3.2\\times$; HFC demonstrates CAI circularity.","Historical unrecoverable-checkpoint scores: CodonOpt exceeds ICOR by 1.52 z-score units. This is not a fold expression gain. CAI and GC differ by arm; later source-pinned rescoring is separate.")
old="Reported positively, this is the circularity result made concrete: \\textbf{single-codon statistics are structurally blind to the sequence-context information CodonOpt exploits}. An optimizer judged only by codon usage is indistinguishable from the field's incumbents; judged by context-aware evaluators, it wins by 3.2$\\times$. The metric chooses the winner; that is the discovery."
fix(old,"This is a retained evaluator-ranking reversal, not proof that codon frequencies cannot capture the relevant information. The ridge evaluator also uses codon-frequency features, while the RF differs in estimator and training protocol. Shared PaxDb labels and surrogate-guided optimization remain possible sources of bias. A causal sequence-context claim needs matched representation/estimator controls and measured expression outcomes.")
fix("($4.0\\times$; paired", "(difference $1.01$ z-score units; paired")
fix("The optimization gain is therefore not an artifact of scoring with the optimized network: it transfers to an independently trained evaluator and to a tRNA-copy-number metric.","The score increase transfers to a separately trained codon-frequency ridge and a tRNA-copy-number metric. This weakens one same-network-only explanation but does not exclude shared-label or objective bias, and it does not validate measured expression.")
fix("Under this third,\nfully independent evaluator", "Under this separately represented evaluator trained on the same abundance labels")
fix("Three evaluators built\non three different representation classes (task-trained CNN, regularized linear\nmodel on sequence, frozen transformer embeddings) now rank CodonOpt first; the\nsingle dissenting evaluator is the one restricted to codon frequencies.","The CNN, ridge and frozen-embedding evaluator rank CodonOpt first in their respective experiments; RF does not. The ridge uses codon-frequency features, so the disagreement is not a simple sequence-context versus bag-of-codons contrast. Evaluator training labels are shared, and experimental conditions differ.")
fix("so 0.627\nis a floor on what a foundation model can extract, not a ceiling.","so 0.627 is a score at the tested representation and split, not a lower bound on achievable prediction or biological signal.")
fix("the\nsingle-split estimate of \\S\\ref{sec:foundation} (0.627) sits inside the nested-CV\nspread, confirming it was not a lucky split.","the single-split estimate of \\S\\ref{sec:foundation} (0.627) is above the reported bootstrap interval for the outer-fold mean, whose upper bound is 0.606. That interval estimates a mean under this resampling procedure, not the distribution of future single-split scores, and cannot certify absence of split selection.")
fix("First, all\nevaluator-performance claims in this report now carry CIs rather than point\nscores.","First, these two archived nested-CV means have reported uncertainty estimates; other evaluator scores remain point estimates. Overlapping training sets and only five outer-fold scores limit a naive fold bootstrap.")
fix("quantifies how much expression signal lives in\ncodon-usage statistics relative to what a general frozen encoder surfaces\nwithout task training", "compares predictive performance of these tested views and estimators; it does not partition biological expression information into representation classes")
fix("that ranking is\nconsistent across evaluator classes with non-overlapping inductive biases.","rankings are evaluator-dependent, and none is an independent measured-expression outcome.")
p.write_text(s);(ROOT/'results/manuscript_claim_consistency.json').write_text(json.dumps(changes,indent=2)+'\n')
